image: Visual Studio 2017
build: off
branches:
  only:
    - master
#- ps: Set-WinSystemLocale ja-JP
#- ps: Start-Sleep -s 5
#- ps: Restart-Computer

#please disable steam moblie guard
environment:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  steam_user:
    secure: hsxtc+FBD98/Nhk5qCeiWg==
  steam_password:
    secure: vFVCpC2RGPS9OufyEfTTlg==
test_script:
  - ps: ./tests/validate.ps1
deploy_script:
  - ps: ./workshop/deploy.ps1
