image: Visual Studio 2017
build: off
branches:
  only:
    - master
#- ps: Set-WinSystemLocale ja-JP
#- ps: Start-Sleep -s 5
#- ps: Restart-Computer

#please disable steam moblie guard
environment:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  steam_user:
    secure: 27TvJgir1/IrhsFs2YPsuQ==
  steam_password:
    secure: jdxBm94E9UgLoODM0CSRUg==
test_script:
  - ps: ./tests/validate.ps1
deploy_script:
  - ps: ./workshop/deploy.ps1
